#include <string.h>
#include <SDL.h>
#include <SDL_image.h>
#include "vector.h"
#include "sprite.h"
#include "simple_logger.h"
#include "background.h"
#include "map.h"
#include "camera.h"
#include "entity.h"